version: '3.7'

networks:
  harvest:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1500

services:

  bot:
    build: ./bot
    container_name: telegram_bot
    networks:
      - harvest

volumes:
  mongo_data: